# Generated by Django 5.1.4 on 2025-01-04 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.FloatField(blank=True, null=True)),
                ('utilities', models.FloatField(blank=True, null=True)),
                ('insurance', models.FloatField(blank=True, null=True)),
                ('transportation', models.FloatField(blank=True, null=True)),
                ('food', models.FloatField(blank=True, null=True)),
                ('healthcare', models.FloatField(blank=True, null=True)),
                ('education', models.FloatField(blank=True, null=True)),
                ('entertainment', models.FloatField(blank=True, null=True)),
                ('savings', models.FloatField(blank=True, null=True)),
                ('loan', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Expenses',
                'verbose_name_plural': 'Expenses',
                'db_table': 'expenses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IncomeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.FloatField(blank=True, null=True)),
                ('other_income', models.CharField(blank=True, max_length=100, null=True)),
                ('other_income_type', models.CharField(blank=True, max_length=100, null=True)),
                ('other_income_amount', models.FloatField(blank=True, null=True)),
                ('other_income_frequency', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Income Details',
                'verbose_name_plural': 'Income Details',
                'db_table': 'income_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=100, null=True)),
                ('dependents', models.IntegerField(blank=True, default=0, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Personal Information',
                'verbose_name_plural': 'Personal Information',
                'db_table': 'personal_information',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SIGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savings_goal', models.FloatField(blank=True, null=True)),
                ('investment_goal', models.FloatField(blank=True, null=True)),
                ('investment_horizon', models.CharField(blank=True, max_length=100, null=True)),
                ('risk_tolerance', models.CharField(blank=True, max_length=100, null=True)),
                ('investment_knowledge', models.CharField(blank=True, max_length=100, null=True)),
                ('investment_experience', models.CharField(blank=True, max_length=100, null=True)),
                ('investment_objective', models.CharField(blank=True, max_length=100, null=True)),
                ('investment_strategy', models.CharField(blank=True, max_length=100, null=True)),
                ('investment_style', models.CharField(blank=True, max_length=100, null=True)),
                ('investment_amount', models.FloatField(blank=True, null=True)),
                ('investment_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('investment_start_date', models.DateField(blank=True, null=True)),
                ('investment_end_date', models.DateField(blank=True, null=True)),
                ('investment_account', models.CharField(blank=True, max_length=100, null=True)),
                ('investment_account_type', models.CharField(blank=True, max_length=100, null=True)),
                ('investment_account_balance', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Savings and Investment Goals',
                'verbose_name_plural': 'Savings and Investment Goals',
                'db_table': 'savings_investment_goals',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserQus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expenses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.expenses')),
                ('income_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.incomedetails')),
                ('personal_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.personalinformation')),
                ('savings_investment_goals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.sigoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Questionnaire',
                'verbose_name_plural': 'User Questionnaire',
                'db_table': 'user_questionnaire',
                'managed': True,
            },
        ),
    ]
