# Generated by Django 5.1.4 on 2025-01-04 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userqus',
            name='expenses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.expenses'),
        ),
        migrations.AlterField(
            model_name='userqus',
            name='income_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.incomedetails'),
        ),
        migrations.AlterField(
            model_name='userqus',
            name='personal_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.personalinformation'),
        ),
        migrations.AlterField(
            model_name='userqus',
            name='savings_investment_goals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.sigoal'),
        ),
    ]
