# Generated by Django 5.1.4 on 2025-01-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0002_alter_userqus_expenses_alter_userqus_income_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userqus',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
