# Generated by Django 5.1.4 on 2025-01-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0003_userqus_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userqus',
            name='user_name',
            field=models.CharField(default='User', max_length=100),
        ),
    ]
