# Generated by Django 5.1.4 on 2025-01-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0006_alter_userqus_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userqus',
            name='advice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
