# Generated by Django 5.1.4 on 2025-01-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0007_userqus_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='loan_interest_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='loan_tenure',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='monthly_income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='other_income',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sigoal',
            name='career_changes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sigoal',
            name='life_events',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sigoal',
            name='major_purchases',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sigoal',
            name='prioritization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
