# Generated by Django 5.1.4 on 2025-01-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0008_expenses_loan_interest_rate_expenses_loan_tenure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='loan_interest_rate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
